# Makefile for [source/physics/RadTrans/RadTransMain/TwoMoment/Thornado/thornado/SandBox/Interface_FLASH/AMD]

RadTrans += HipModule.o \
            RocblasModule.o \
            RocsolverModule.o \
            RocsparseModule.o \
            HipblasModule.o \
            HipsparseModule.o
