# Makefile for [source/physics/RadTrans/RadTransMain/TwoMoment/Thornado/thornado/SandBox/Interface_FLASH/Relativistic]

RadTrans += TwoMoment_OpacityModule.o \
            TwoMoment_DiscretizationModule_Collisions.o
