# Makefile for [source/physics/RadTrans/RadTransMain/TwoMoment/Thornado/thornado/SandBox/Interface_FLASH/NVIDIA]

RadTrans += CudaModule.o \
            CublasModule.o \
            CusolverModule.o \
            CusparseModule.o
