# Makefile for [source/physics/RadTrans/RadTransMain/TwoMoment/Thornado/thornado/SandBox/Interface_FLASH/OrderV]

RadTrans += TwoMoment_TroubledCellIndicatorModule.o \
            TwoMoment_OpacityModule.o \
            TwoMoment_DiscretizationModule_Collisions.o
